# Generated by Django 4.2.4 on 2023-09-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InputToClean",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cname", models.CharField(blank=True, max_length=50, null=True)),
                ("mname", models.CharField(blank=True, max_length=50, null=True)),
                ("sname", models.CharField(blank=True, max_length=50, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("svolume", models.FloatField(blank=True, null=True)),
                ("mount", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "input_to_clean",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        db_collation="utf8_general_ci",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("baby", models.IntegerField(blank=True, null=True)),
                ("menstruation", models.IntegerField(blank=True, null=True)),
                (
                    "loyalty",
                    models.CharField(
                        blank=True,
                        db_collation="utf8_general_ci",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "identity",
                    models.CharField(
                        blank=True,
                        db_collation="utf8_general_ci",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tendency",
                    models.CharField(
                        blank=True,
                        db_collation="utf8_general_ci",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "output",
                "managed": False,
            },
        ),
    ]
